#Matriks

In [7]:
import matplotlib
import numpy as np

In [8]:
def crout(A: np.ndarray):

    L = np.zeros((3, 3))
    U = np.zeros((3, 3))

    for k in range(0, 3):
        U[k, k] = 1

        for j in range(k, 3):
            sum0 = sum(L[k, s] * U[s, j] for s in range(1, k-1))
            L[k, j] = A[k, j] - sum0

        for j in range(k, 3):
            sum1 = sum(L[k, s] * U[s, j] for s in range(1, k-1))
            U[k, j] = (A[k, j] - sum1) / L[k, k]

    print(" L =", '\n', L, '\n', " U =", '\n', U)
    return L, U

In [9]:
A = np.array([[2.0, -5.0, 1.0], [-1.0, 3.0, -1.0], [3.0, -4.0, 2.0]])
crout(A)

 L = 
 [[ 2. -5.  1.]
 [ 0.  3. -1.]
 [ 0.  0.  2.]] 
  U = 
 [[ 1.         -2.5         0.5       ]
 [ 0.          1.         -0.33333333]
 [ 0.          0.          1.        ]]


(array([[ 2., -5.,  1.],
        [ 0.,  3., -1.],
        [ 0.,  0.,  2.]]),
 array([[ 1.        , -2.5       ,  0.5       ],
        [ 0.        ,  1.        , -0.33333333],
        [ 0.        ,  0.        ,  1.        ]]))